### ISSUE TITLE
Address high TBT

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#104]
[Page speed test](https://pagespeed.web.dev/analysis/https-main--zeiss--hlxsites-hlx-live-en-semiconductor-manufacturing-technology-news-and-events-smt-press-releases-2023-new-multifunctional-factory-in-wetzlar/zaijp8gem4?form_factor=mobile)

<img width="951" alt="image" src="https://user-images.githubusercontent.com/1191451/231987640-775e2587-650e-47f1-9f14-2731d646a3bb.png">

**Comment by tmaret** [comment]
This is likely due to Zeiss GTM configuration. Here are the evidences:

1. Current `main` branch serves [GTM-WWQQS7V](https://www.googletagmanager.com/gtm.js?id=GTM-WWQQS7V) on `.page` which is 474KB large and [yields > 2s TBT](https://pagespeed.web.dev/analysis/https-main--zeiss--hlxsites-hlx-page/x5dmras6m2?form_factor=mobile)

2. Branch `issue-116` serves [GTM-T6MZWTJ](https://www.googletagmanager.com/gtm.js?id=GTM-T6MZWTJ) on `.page` which is 267KB large and [yields < 10ms TBT](https://pagespeed.web.dev/analysis/https-issue-116--zeiss--hlxsites-hlx-page/av9bm5ebvl?form_factor=mobile)

**Comment by tmaret** [comment]
Loading delayed content after 6 seconds instead of 3 seconds appears to be an effective mitigation applied in https://github.com/hlxsites/zeiss/pull/120

If Zeiss GTM can be cleaned up and/or simplified we could reduce the delay.
