### ISSUE TITLE
Performance discrepancy between Lighthouse, PageSpeed, and GTmetrix 

### ISSUE THREAD

**Issue by mohamadhjeij** [hlxsites/zeiss#221]
A performance index difference was observed when conducting a simple performance test using 3 different tools. 

URL:
https://main--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases-21-Apr-23-bkp/european-inventor-award

Lighthouse:
![Screenshot 2023-05-17 at 10 55 23](https://github.com/hlxsites/zeiss/assets/125564950/4379de66-60ff-42cc-8d38-6c5570857664)

GTMetrix:
![Screenshot 2023-05-17 at 10 57 26](https://github.com/hlxsites/zeiss/assets/125564950/3f4cdead-b94c-4f6c-aa5a-b07dbb12cc5c)

PageSpeed
![Screenshot 2023-05-17 at 10 59 37](https://github.com/hlxsites/zeiss/assets/125564950/45b56bda-444c-4e13-a9e9-41c4d8fa2fa5)

**Comment by bosschaert** [comment]
Hi @mohamadhjeij 

I think the Lighthouse and PageSpeed ones are essentially the same but the Lighthouse one is running from your local browser, so that might be affected by local network performance. I haven't used GTMetrics before but we generally focus on the PageSpeed metrics. 

In the screenshot below you can see averages of multiple PageSpeed runs (times in ms) and these results seem generally pretty good.

<img width="808" alt="Screenshot 2023-05-17 at 14 45 05" src="https://github.com/hlxsites/zeiss/assets/226514/1ded87d6-1ad4-4bca-bbe1-521045a2ad2c">

One thing to mention is that both the LHS and the PS results only show 92 on best practices. These relate to CORS requests that are not yet enabled. I am working on a fallback for these requests so that they work fine in any case.

Another thing I noticed is that you used the .hlx.page URL. These are the preview URLs. The .hlx.live URLs are the production ones which might have better performance as these are cached if possible.
